[project]
name = "fmcpe"
version = "0.1.0"
authors = [{name = "pruhlman", email = "pierre-louis.ruhlmann@inria.fr"}]

[tool.basedpyright]
venv = "fmcpe"
typeCheckingMode = "basic"
reportAssignmentType = "none"

[tool.ruff]
line-length = 100
